FROM python:3

ADD import_csv.py /
ADD Schema.py /
ADD Strategies/BuyDipStrategy.py /
ADD Strategies/MacdStrategy.py /
ADD Strategies/EmaCrossStrategy.py /
ADD Strategies/Stochastic1.py /
ADD tools.py /
ADD build_ta_lib /
ADD requirements.txt /

RUN ["/bin/bash", "-c", "ls -la"]
RUN ["/bin/bash", "-c", "./build_ta_lib"]

RUN pip install -r requirements.txt

CMD [ "python", "./import_csv.py", "-h" ]
