FROM python:3

ADD run_backtest.py /
ADD Schema.py /

ADD Strategies/BuyDipStrategy.py /
ADD Strategies/MacdStrategy.py /
ADD Strategies/SmaCrossStrategy.py /
ADD Strategies/Stochastic1.py /

ADD tools.py /
ADD build_ta_lib /
ADD requirements.txt /

RUN ["/bin/bash", "-c", "ls -la"]
RUN ["/bin/bash", "-c", "./build_ta_lib"]

RUN pip install -r requirements.txt

CMD [ "python", "./run_backtest.py", "-h" ]
